@startuml
interface domain.fine.FineStrategy {
~ int calculateFine(int)
}

class presentation.Main {
- {static} Scanner input
- {static} String ENTER_CHOICE
- {static} String INVALID_MSG
- {static} String PROMPT_BOOK_ISBN
- {static} String PROMPT_CD_ID
- {static} String PROMPT_SEARCH_TEXT
+ {static} void main(String[])
- {static} void saveAll(UserService,BookService,CDService,LoanService,CDLoanService,AdminService)
- {static} void mainMenu(AdminService,LibraryService,BookService,CDService,UserService,LoanService,CDLoanService)
- {static} void loginRoleMenu(AdminService,LibraryService,BookService,CDService,UserService)
- {static} void adminLoginFlow(AdminService,LibraryService,BookService,CDService,UserService)
- {static} void adminAddBook(BookService)
- {static} void adminAddCD(CDService)
- {static} void adminUnregisterUser(UserService)
- {static} void librarianMenu(LibraryService)
- {static} void userLoginFlow(UserService,LibraryService,BookService,CDService)
- {static} void userSearchBooks(BookService)
- {static} void userSearchCDs(CDService)
- {static} void userBorrowBook(User,LibraryService,BookService)
- {static} void userBorrowCD(User,LibraryService,CDService)
- {static} void userReturnBook(User,LibraryService,BookService)
- {static} void userReturnCD(User,LibraryService,CDService)
- {static} void userViewStatus(User)
- {static} void userPayFine(User,UserService)
- {static} int getInt()
}


class service.ReminderService {
- List<Observer> observers
+ boolean addObserver(Observer)
- void notifyObservers(User,String)
+ void sendReminders(List<Loan>,List<CDLoan>)
}


class service.LoanService {
- List<Loan> loans
- BookService bookService
- UserService userService
- {static} String LOANS_FILE
+ boolean createLoan(User,Book)
+ void saveAllLoansToFile()
+ void loadLoansFromFile()
+ boolean returnLoan(User,Book)
+ List<Loan> getOverdueLoans()
+ List<Loan> getAllLoans()
}


class domain.CD {
- String title
- String artist
- String id
- boolean available
- LocalDate borrowDate
- LocalDate dueDate
+ void borrowCD(LocalDate)
+ void borrowCD()
+ void returnCD()
+ boolean isOverdue(LocalDate)
+ boolean isOverdue()
+ int getRemainingDays(LocalDate)
+ boolean isAvailable()
+ LocalDate getBorrowDate()
+ LocalDate getDueDate()
+ String getTitle()
+ String getArtist()
+ String getId()
+ void setBorrowDate(LocalDate)
+ void setDueDate(LocalDate)
+ String toString()
}


class domain.fine.BookFineStrategy {
+ int calculateFine(int)
}

class service.LibrarianService {
- List<Librarian> librarians
- LibraryService libraryService
- Librarian loggedInLibrarian
- {static} String LIBRARIANS_FILE
+ boolean addLibrarian(int,String,String)
+ boolean login(String,String)
+ void logout()
+ boolean isLoggedIn()
+ Librarian getLoggedInLibrarian()
+ List<Librarian> getAllLibrarians()
+ List<Loan> getOverdueBooks()
+ List<CDLoan> getOverdueCDs()
+ int getTotalOverdueItems()
+ void saveLibrariansToFile()
+ void loadLibrariansFromFile()
}


class file.FileManager {
+ {static} List<String> readLines(String)
+ {static} void writeLines(String,List<String>)
+ {static} void appendLine(String,String)
}

class service.LibraryService {
- UserService userService
- BookService bookService
- LoanService loanService
- CDLoanService cdLoanService
- ReminderService reminderService
+ User findUserByName(String)
+ Book findBookByISBN(String)
+ CD findCDById(List<CD>,String)
+ User findLoanUser(Book)
+ boolean borrowBook(User,Book)
+ boolean returnBook(User,Book)
+ boolean borrowCD(User,CD)
+ boolean returnCD(User,CD)
- void cdSave()
+ List<Loan> getOverdueLoans()
+ List<CDLoan> getOverdueCDLoans()
+ List<Loan> getAllLoans()
+ List<CDLoan> getAllCDLoans()
+ void sendOverdueReminders()
+ List<User> getAllUsers()
+ List<Book> getAllBooks()
}


class service.UserService {
- List<User> users
- {static} String USERS_FILE
+ boolean addUser(String,String)
+ boolean addUser(String)
+ void saveUsers()
+ void loadUsersFromFile()
+ User findUserByName(String)
+ List<User> getAllUsers()
+ boolean canBorrow(User)
+ boolean unregisterUser(User)
}


class domain.fine.CDFineStrategy {
+ int calculateFine(int)
}

class service.AdminService {
- List<Admin> admins
- Admin loggedInAdmin
- {static} String ADMINS_FILE
+ boolean addAdmin(String,int,String)
+ boolean login(String,String)
+ void logout()
+ boolean isAdminLoggedIn()
+ Admin getLoggedInAdmin()
+ List<Admin> getAllAdmins()
+ void saveAdminsToFile()
+ void loadAdminsFromFile()
}


class domain.Librarian {
- int librarianId
- String name
- String password
- boolean loggedIn
+ boolean login(String,String)
+ void logout()
+ boolean isLoggedIn()
+ int getLibrarianId()
+ String getName()
+ String getPassword()
+ void setPassword(String)
+ String toString()
}


class domain.Loan {
- User user
- Book book
- LocalDate borrowDate
- LocalDate dueDate
- FineStrategy fineStrategy
- boolean active
+ void returnBook()
+ boolean isActive()
+ boolean isOverdue(LocalDate)
+ boolean isOverdue()
+ int getOverdueDays()
+ int calculateFine()
+ void setBorrowDate(LocalDate)
+ void setDueDate(LocalDate)
+ void setFineStrategy(FineStrategy)
+ User getUser()
+ Book getBook()
+ LocalDate getBorrowDate()
+ LocalDate getDueDate()
+ FineStrategy getFineStrategy()
+ String toString()
}


interface notification.Observer {
~ void notify(User,String)
}

class domain.CDLoan {
- User user
- CD cd
- LocalDate borrowDate
- LocalDate dueDate
- FineStrategy fineStrategy
- boolean active
+ void returnCD()
+ boolean isActive()
+ boolean isOverdue(LocalDate)
+ boolean isOverdue()
+ int getOverdueDays()
+ int calculateFine()
+ void setBorrowDate(LocalDate)
+ void setDueDate(LocalDate)
+ User getUser()
+ CD getCD()
+ LocalDate getBorrowDate()
+ LocalDate getDueDate()
+ String toString()
}


class service.BookService {
- List<Book> books
- {static} String BOOKS_FILE
+ boolean addBook(String,String,String)
+ void saveBooksToFile()
- boolean parseBooleanStrict(String)
- LocalDate parseDateOrNull(String)
+ void loadBooksFromFile()
+ List<Book> search(String)
+ Book findBookByISBN(String)
+ List<Book> getAllBooks()
}


class service.CDService {
- List<CD> cds
- {static} String CD_FILE
+ boolean addCD(String,String,String)
+ void saveCDsToFile()
- boolean parseBooleanStrict(String)
- LocalDate parseDateOrNull(String)
+ void loadCDsFromFile()
+ List<CD> search(String)
+ CD findCDById(String)
+ List<CD> getAllCDs()
}


class domain.Book {
- String title
- String author
- String isbn
- boolean available
- LocalDate borrowDate
- LocalDate dueDate
+ boolean isAvailable()
+ void borrowBook(LocalDate)
+ void borrowBook()
+ void returnBook()
+ boolean isOverdue(LocalDate)
+ boolean isOverdue()
+ int getRemainingDays(LocalDate)
+ LocalDate getDueDate()
+ LocalDate getBorrowDate()
+ String getTitle()
+ String getAuthor()
+ String getIsbn()
+ boolean isBorrowed()
+ void setAvailable(boolean)
+ void setBorrowDate(LocalDate)
+ void setDueDate(LocalDate)
+ String toString()
}


class domain.User {
- String name
- String email
- double fineBalance
- List<Loan> activeBookLoans
- List<CDLoan> activeCDLoans
+ String getUserName()
+ String getEmail()
+ double getFineBalance()
+ List<Loan> getActiveBookLoans()
+ List<CDLoan> getActiveCDLoans()
+ void setEmail(String)
+ void setFineBalance(double)
+ void addLoan(Loan)
+ void addCDLoan(CDLoan)
+ void returnLoan(Loan)
+ void returnCDLoan(CDLoan)
+ boolean hasOverdueLoans()
+ int getOverdueCount()
+ void payFine(double)
+ boolean canBeUnregistered()
+ String toString()
}


class notification.MockNotifier {
- List<String> messages
+ void notify(User,String)
+ List<String> getMessages()
}


class domain.Admin {
- String userName
- int adminId
- String password
- boolean loggedIn
+ boolean login(String,String)
+ void logout()
+ boolean isLoggedIn()
+ String getUserName()
+ int getAdminId()
+ String getPassword()
+ void setUserName(String)
+ void setPassword(String)
+ String toString()
}


class notification.EmailNotifier {
- String senderEmail
- String appPassword
+ void notify(User,String)
}


class service.CDLoanService {
- List<CDLoan> cdLoans
- BookService bookService
- UserService userService
- {static} String LOANS_FILE
+ boolean createCDLoan(User,CD)
+ boolean returnCDLoan(User,CD)
+ void saveAllLoansToFile()
+ void loadCDLoansFromFile(List<CD>)
+ List<CDLoan> getOverdueCDLoans()
+ List<CDLoan> getAllCDLoans()
}




domain.fine.FineStrategy <|.. domain.fine.BookFineStrategy
domain.fine.FineStrategy <|.. domain.fine.CDFineStrategy
notification.Observer <|.. notification.MockNotifier
notification.Observer <|.. notification.EmailNotifier
@enduml